# application.yaml
spring:
  application:
    name: robokey
server:
  port: 8080  # Port for the REST controller
  error:
    whitelabel:
      enabled: false
app: # You can edit these settings, but be careful, a rogue keyboard can cause chaos
  consoleCommands: true # can be used to turn off the console command processor
  gui: true # enable the gui window, if false its hidden
  darkMode: false
  mode: PHYSICAL  # Options: PHYSICAL, LOCAL, LOG
  comPort: COM3  # Required if mode is PHYSICAL/HARDWARE
  logFilePath: logs/dummy.log  # Required if mode is LOG
  keyboard: # keyboard settings only apply to physical keyboards
    allJitter: true # note the jitter values will only be applied to the physical keyboard type
    output: true # If false and using a local keyboard, keystrokes will just be logged
    uiExtraDelay: true # use an extra initial delay when the gui is used, it will always do this for a local keyboard
    initialDelay: 3000 # sets an initial delay to allow the cursor to be moved to the correct place when used locally, used by physical keyboards
    useBusyState: true # dont send data to the arduino untill it sends a status not busy message
    press: # ignored for local (AWT Robot) keyboards
      jitter: false
      jitterMax: 100
      time: 100
    delay: # ignored for local (AWT Robot) keyboards
      jitter: false
      jitterMax: 300
      time: 300
  fileWatcher:
    enabled: true
    winfilePath: "C:\\data\\robo_keyboard_commands.txt"
    posixFilePath: /tmp/robo_keyboard_commands.txt
    createFile: true # create the file if it doesnt exist
    charset: UTF-8 # auto tries to guess the charset from the file, either auto or the name of the charset.
    fallBackCharset: UTF-8 # if auto or invalid will use os defaults of  UFF-8
logger:
  levels:
    io.micronaut: DEBUG
    org.hibernate: DEBUG
    io.micronaut.data: DEBUG