spring:
  application:
    name: robokey
server:
  port: 8080  # Port for the REST controller
  error:
    whitelabel:
      enabled: false

app:
  console-commands: true  # Can be used to turn off the console command processor
  gui: true  # Enable the GUI window; if false, it's hidden
  dark-mode: false
  mode: PHYSICAL  # Options: PHYSICAL, LOCAL, LOG
  com-port: COM3  # Required if mode is PHYSICAL/HARDWARE
  log-file-path: logs/dummy.log  # Required if mode is LOG
  debug: true
  keyboard:
    output: true  # If false and using a local keyboard, keystrokes will just be logged
    initial-delay: 3000  # Sets an initial delay for cursor positioning when used locally
    all-jitter: true  # Jitter values only apply to the physical keyboard type
    ui-extra-delay: true  # Use an extra initial delay when the GUI is used
    use-busy-state: true  # Don't send data to the Arduino until it sends a "not busy" status
    press:
      jitter: false
      jitter-max: 100
      time: 100
    interval:
      jitter: false
      jitter-max: 500
      time: 300
  file-watcher:
    enabled: true
    win-file-path: "C:\\data\\robo_keyboard_commands.txt"
    posix-file-path: /tmp/robo_keyboard_commands.txt
    create-file: true
    charset: UTF-8
    fall-back-charset: UTF-8

logging:
  level:
    io.micronaut: DEBUG
    org.hibernate: DEBUG
    io.micronaut.data: DEBUG
